#!/bin/bash
while read -r line
do
    if [ "$(echo $line | cut -c1-10)" == "app config" ]
    then
        IFS=' ' read -r -a array <<< "$line"
        branch_name="${array[1]}"
        echo -e "\e[4mPUSH TO BRANCH NAME : $branch_name\e[24m"
        IFS='-' read -r -a array <<< "$branch_name"
        branch_id="${array[1]}"
        if [ "$(echo "$line" | awk '{split($0,a,"-"); print a[1]}')"  == "* feature" ]
        then
            header="feature #$branch_id"
        fi

        if [ "$(echo "$line" | awk '{split($0,a,"-"); print a[1]}')"  == "* bug" ]
        then
            header="bug #$branch_id"
        fi
        if [ "$1" = "-p" ]
        then
            git pull origin "$branch_name"
        elif [ "$1" = "-c" ]
        then
            git stash save -u "jig stash save for $branch_name"
            git checkout -b "$2" origin/master
            echo -e "\e[4mCREATE : $header $1\e[24m"
        else
            echo -e "\e[4mCOMMIT MESSAGE : $header $1\e[24m"
            git add .
            git commit -m "$header $1"
            git push origin "$branch_name"
        fi
    break
    fi
done < <(git branch)